name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'android/**'
      - 'client/**'
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web assets
      run: npm run build
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create release keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release.keystore
        
    - name: Build AAB
      run: |
        cd android
        ./gradlew bundleRelease \
          -PMYAPP_UPLOAD_STORE_FILE=../app/release.keystore \
          -PMYAPP_UPLOAD_STORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
          -PMYAPP_UPLOAD_KEY_ALIAS="${{ secrets.KEY_ALIAS }}" \
          -PMYAPP_UPLOAD_KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
          
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: MarketGrow-v5.3-VersionCode15-FINAL
        path: android/app/build/outputs/bundle/release/app-release.aab
        
    - name: Rename and copy AAB
      run: |
        cp android/app/build/outputs/bundle/release/app-release.aab MarketGrow-v5.3-VersionCode15-FINAL.aab
        
    - name: Upload final AAB
      uses: actions/upload-artifact@v4
      with:
        name: MarketGrow-Ready-For-Upload
        path: MarketGrow-v5.3-VersionCode15-FINAL.aab
